#obj-$(CONFIG_DVB_CS75XX_TS) = cs752x_ts.o mxl241sf_driver.o MxL241SF_OEM_Drv.o \
#		MxL241SF_PhyCfg.o MxL241SF_PhyCtrlApi.o


cs75xx_ts-objs = cs752x_ts.o 

obj-$(CONFIG_DVB_CS75XX_TS) += cs75xx_ts.o

EXTRA_CFLAGS = -Idrivers/media/dvb/dvb-core/ -Idrivers/media/dvb/frontends/

