# CS75XX Platform Support
snd-soc-cs75xx-objs := cs75xx_snd_sport.o cwda15.o cs75xx_snd_plat.o cs75xx_snd_dai.o

obj-$(CONFIG_SND_CS75XX_SOC) += snd-soc-cs75xx.o

# CS75XX Machine Support
snd-soc-evm-objs := cs75xx_snd_evm.o

obj-$(CONFIG_SND_CS75XX_SOC_EVM) += snd-soc-evm.o
