#
# Makefile for etherhook.
#
EXTRA_CFLAGS += -I$(srctree)/drivers/net/ethernet/cs752x/src/ni
EXTRA_CFLAGS += -I$(srctree)/drivers/net/ethernet/cs752x/src/qm
EXTRA_CFLAGS += -I$(srctree)/drivers/net/ethernet/cs752x/src/diagnostic
EXTRA_CFLAGS += -I$(srctree)/drivers/net/ethernet/cs752x/src/fe/include
EXTRA_CFLAGS += -I$(srctree)/drivers/net/ethernet/cs752x/src/include
EXTRA_CFLAGS += -I$(srctree)/drivers/net/ethernet/cs752x/src/sch
EXTRA_CFLAGS += -I$(srctree)/drivers/net/ethernet/cs752x/src/tm

obj-y += etherhook.o
